# OBSERVAÇÕES

�

In [1]:
import numpy as np
import pandas as pd

---

# ESCOLAS 2013-2017

In [2]:
dtypeEscola = {
    "ano_censo": int,
    "cod_escola_inep" : object,
    "regiao" : "category",
    "unidade_federativa" : "category",
    "mesoregiao" : "category",
    "microregiao" : object,
    "municipio" : object,
    "tp_dependencia" : "category",
    "tp_dependencia_desc" : "category",
    "tp_rede_publica" : bool,
    "rede_publica_desc" : "category",
    "in_somente_matriculas_ac_ou_aee" : bool,
    "tp_rede" : "category",
    "tp_rede_nome" : object,
    "tp_rede_cod" : object,
    "nome_escola" : object,
    "num_matriculas" : int,
    "num_estudantes" : int,
    "in_comum_creche" : bool,
    "in_comum_pre" : bool,
    "in_comum_fund_ai" : bool,
    "in_comum_fund_af" : bool,
    "in_comum_medio_medio" : bool,
    "in_comum_medio_integrado" : bool,
    "in_comum_medio_normal" : bool,
    "num_estudantes_ensino_infantil" : int,
    "num_estudantes_ensino_fund_anos_iniciais" : int,
    "num_estudantes_ensino_fund_anos_finais" : int,
    "num_estudantes_ensino_medio_propedeutico" : int,
    "num_estudantes_fund_1_ano" : int,
    "num_estudantes_fund_2_ano" : int,
    "num_estudantes_fund_3_ano" : int,
    "num_estudantes_fund_4_ano" : int,
    "num_estudantes_fund_5_ano" : int,
    "num_estudantes_fund_6_ano" : int,
    "num_estudantes_fund_7_ano" : int,
    "num_estudantes_fund_8_ano" : int,
    "num_estudantes_fund_9_ano" : int,
    "num_estudantes_medio_1_serie" : int,
    "num_estudantes_medio_2_serie" : int,
    "num_estudantes_medio_3_serie" : int,
    "num_estudantes_medio_4_serie" : int,
    "num_estudantes_medio_nao_seriada" : int,
    "num_turmas" : int,
    "tp_situacao_funcionamento" : "category",
    "tp_situacao_funcionamento_desc" : "category",
    "in_em_atividade" : bool,
    "tp_localizacao" : "category",
    "tp_localizacao_desc" : "category",
    "tp_categoria_escola_privada" : "category",
    "tp_categoria_escola_privada_desc" : "category",
    "in_conveniada_pp" : bool,
    "in_conveniada_pp_desc" : bool,
    "tp_convenio_poder_publico" : "category",
    "tp_convenio_poder_publico_desc" : "category",
    "in_local_func_predio_escolar" : bool,
    "tp_ocupacao_predio_escolar" : "category",
    "tp_ocupacao_predio_escolar_desc" : "category",
    "in_local_func_salas_empresa" : bool,
    "in_local_func_socioeducativo" : bool,
    "in_local_func_unid_prisional" : bool,
    "in_local_func_prisional_socio" : bool,
    "in_local_func_templo_igreja" : bool,
    "in_local_func_casa_professor" : bool,
    "in_local_func_galpao" : bool,
    "tp_ocupacao_galpao" : "category",
    "tp_ocupacao_galpao_desc" : "category",
    "in_local_func_salas_outra_esc" : bool,
    "in_local_func_outros" : bool,
    "in_predio_compartilhado" : bool,
    "in_agua_filtrada" : bool,
    "in_agua_rede_publica" : bool,
    "in_agua_poco_artesiano" : bool,
    "in_agua_cacimba" : bool,
    "in_agua_fonte_rio" : bool,
    "in_agua_inexistente" : bool,
    "in_energia_rede_publica" : bool,
    "in_energia_gerador" : bool,
    "in_energia_outros" : bool,
    "in_energia_inexistente" : bool,
    "in_esgoto_rede_publica" : bool,
    "in_esgoto_fossa" : bool,
    "in_esgoto_inexistente" : bool,
    "in_lixo_coleta_periodica" : bool,
    "in_lixo_queima" : bool,
    "in_lixo_joga_outra_area" : bool,
    "in_lixo_recicla" : bool,
    "in_lixo_enterra" : bool,
    "in_lixo_outros" : bool,
    "in_sala_diretoria" : bool,
    "in_sala_professor" : bool,
    "in_laboratorio_informatica" : bool,
    "in_laboratorio_ciencias" : bool,
    "in_sala_atendimento_especial" : bool,
    "in_quadra_esportes_coberta" : bool,
    "in_quadra_esportes_descoberta" : bool,
    "in_quadra_esportes" : bool,
    "in_cozinha" : bool,
    "in_biblioteca" : bool,
    "in_sala_leitura" : bool,
    "in_biblioteca_sala_leitura" : bool,
    "in_parque_infantil" : bool,
    "in_bercario" : bool,
    "in_banheiro_fora_predio" : bool,
    "in_banheiro_dentro_predio" : bool,
    "in_banheiro_ei" : bool,
    "in_banheiro_pne" : bool,
    "in_dependencias_pne" : bool,
    "in_secretaria" : bool,
    "in_banheiro_chuveiro" : bool,
    "in_refeitorio" : bool,
    "in_despensa" : bool,
    "in_almoxarifado" : bool,
    "in_auditorio" : bool,
    "in_patio_coberto" : bool,
    "in_patio_descoberto" : bool,
    "in_alojam_aluno" : bool,
    "in_alojam_professor" : bool,
    "in_area_verde" : bool,
    "in_lavanderia" : bool,
    "in_dependencias_outras" : bool,
    "num_salas_existentes" : int,
    "num_salas_utilizadas" : int,
    "in_equip_tv" : int,
    "in_equip_videocassete" : bool,
    "in_equip_dvd" : bool,
    "in_equip_parabolica" : bool,
    "in_equip_copiadora" : bool,
    "in_equip_retroprojetor" : bool,
    "in_equip_impressora" : bool,
    "in_equip_impressora_mult" : bool,
    "in_equip_som" : bool,
    "in_equip_multimidia" : bool,
    "in_equip_fax" : bool,
    "in_equip_foto" : bool,
    "in_computador" : bool,
    "num_equip_tv" : int,
    "num_equip_videocassete" : int,
    "num_equip_dvd" : int,
    "num_equip_parabolica" : int,
    "num_equip_copiadora" : int,
    "num_equip_retroprojetor" : int,
    "num_equip_impressora" : int,
    "num_equip_impressora_mult" : int,
    "num_equip_som" : int,
    "num_equip_multimidia" : int,
    "num_equip_fax" : int,
    "num_equip_foto" : int,
    "num_computador" : int,
    "num_comp_administrativo" : int,
    "num_comp_aluno" : int,
    "in_internet" : int,
    "in_banda_larga" : bool,
    "num_funcionarios" : int,
    "in_alimentacao" : bool,
    "num_professores" : int,
    "num_professores_em_regencia" : int,
    "num_professores_em_regencia_fund_ai" : int,
    "num_professores_em_regencia_fund_af" : int,
    "num_professores_em_regencia_ens_medio" : int,
    "tp_aee" : "category",
    "tp_aee_desc" : "category",
    "tp_atividade_complementar" : "category",
    "tp_atividade_complementar_desc" : "category",
    "in_fundamental_ciclos" : bool,
    "tp_localizacao_diferenciada" : "category",
    "tp_localizacao_diferenciada_desc" : "category",
    "in_material_esp_quilombola" : bool,
    "in_material_esp_indigena" : bool,
    "in_material_esp_nao_utiliza" : bool,
    "in_educacao_indigena" : bool,
    "tp_indigena_lingua" : "category",
    "tp_indigena_lingua_desc" : "category",
    "co_lingua_indigena" : object,
    "in_brasil_alfabetizado" : bool,
    "in_final_semana" : bool,
    "in_formacao_alternancia" : bool,
    "cod_municipio" : object,
    "num_matriculas_ensino_integral" : int,
    "num_estudantes_ensino_integral" : int,
    "tp_integral" : bool,
    "cod_ibge_uf" : object
}

featuresEscola = list(dtypeEscola.keys())

In [3]:
def readcsv(filename, dictFeatures, listFeatures) :
    
    with open(filename , 'r') as file :
        df = pd.read_csv(file, usecols=listFeatures,
                                  header=0, index_col=None, sep=';', 
                                  low_memory=False, encoding='utf-8', 
                                  na_filter=True)
    
    for feature in df.columns :
        if dictFeatures[feature] == int :
            df[feature] = df[feature].fillna(0).astype(int)
        if dictFeatures[feature] == float :
            df[feature] = df[feature].fillna(0).astype(float)
        if dictFeatures[feature] == bool :
            df[feature] = df[feature].astype(bool)
        if dictFeatures[feature] == "category" :
            df[feature] = df[feature].astype("category")
            
    return df

In [4]:
escolas2017 = readcsv('escolas/escolas2017.csv', dtypeEscola, featuresEscola)

In [6]:
escolas2017.head()

,ano_censo,cod_escola_inep,regiao,unidade_federativa,mesoregiao,microregiao,municipio,tp_dependencia,tp_dependencia_desc,tp_rede_publica,...,tp_indigena_lingua_desc,co_lingua_indigena,in_brasil_alfabetizado,in_final_semana,in_formacao_alternancia,cod_municipio,num_matriculas_ensino_integral,num_estudantes_ensino_integral,tp_integral,cod_ibge_uf
0,2017,11021012,Norte,Rondônia,Leste Rondoniense,Ji-Paraná,Vale do Paraíso,3,Municipal,True,...,NaN,NaN,False,False,False,1101807,0,0,False,11
1,2017,11037288,Norte,Rondônia,Leste Rondoniense,Ji-Paraná,Urupá,4,Privada,True,...,NaN,NaN,False,False,False,1101708,0,0,False,11
2,2017,11045787,Norte,Rondônia,Leste Rondoniense,Ariquemes,Machadinho D'Oeste,3,Municipal,True,...,NaN,NaN,False,False,False,1100130,0,0,False,11
3,2017,11010088,Norte,Rondônia,Leste Rondoniense,Ariquemes,Alto Paraíso,3,Municipal,True,...,NaN,NaN,False,False,False,1100403,0,0,False,11
4,2017,11040203,Norte,Rondônia,Leste Rondoniense,Ji-Paraná,Nova União,3,Municipal,True,...,NaN,NaN,False,False,False,1101435,0,0,False,11

In [9]:
escolas2015 = readcsv('escolas/escolas2015.csv', dtypeEscola, featuresEscola)

In [10]:
escolas2015.head()

,ano_censo,cod_escola_inep,regiao,unidade_federativa,mesoregiao,microregiao,municipio,tp_dependencia,tp_dependencia_desc,tp_rede_publica,...,tp_indigena_lingua_desc,co_lingua_indigena,in_brasil_alfabetizado,in_final_semana,in_formacao_alternancia,cod_municipio,num_matriculas_ensino_integral,num_estudantes_ensino_integral,tp_integral,cod_ibge_uf
0,2015,14006111,Norte,Roraima,Norte de Roraima,Boa Vista,Boa Vista,1,Federal,True,...,NaN,NaN,False,False,False,1400100,0,0,False,14
1,2015,15038688,Norte,Pará,Metropolitana de Belém,Belém,Belém,1,Federal,True,...,NaN,NaN,False,True,False,1501402,1,1,True,15
2,2015,12011410,Norte,Acre,Vale do Acre,Rio Branco,Rio Branco,1,Federal,True,...,NaN,NaN,False,False,False,1200401,1,1,True,12
3,2015,15039153,Norte,Pará,Metropolitana de Belém,Belém,Belém,1,Federal,True,...,NaN,NaN,False,False,False,1501402,0,0,False,15
4,2015,21000492,Nordeste,Maranhão,Norte Maranhense,Litoral Ocidental Maranhense,Alcântara,1,Federal,True,...,NaN,NaN,False,False,False,2100204,0,0,False,21

In [7]:
escolas2013 = readcsv('escolas/escolas2013.csv', dtypeEscola, featuresEscola)

In [8]:
escolas2013.head()

,ano_censo,cod_escola_inep,regiao,unidade_federativa,mesoregiao,microregiao,municipio,tp_dependencia,tp_dependencia_desc,tp_rede_publica,...,tp_indigena_lingua_desc,co_lingua_indigena,in_brasil_alfabetizado,in_final_semana,in_formacao_alternancia,cod_municipio,num_matriculas_ensino_integral,num_estudantes_ensino_integral,tp_integral,cod_ibge_uf
0,2013,12031437,Norte,Acre,Vale do Acre,Rio Branco,Rio Branco,1,Federal,True,...,NaN,NaN,False,False,False,1200401,0,0,False,12
1,2013,15575390,Norte,Pará,Sudoeste Paraense,Altamira,Medicilândia,1,Federal,True,...,NaN,NaN,False,False,False,1504455,0,0,False,15
2,2013,16007190,Norte,Amapá,Sul do Amapá,Macapá,Macapá,1,Federal,True,...,NaN,NaN,False,False,False,1600303,0,0,False,16
3,2013,21268878,Nordeste,Maranhão,Norte Maranhense,Baixada Maranhense,Igarapé do Meio,1,Federal,True,...,NaN,NaN,False,False,False,2105153,0,0,False,21
4,2013,22057528,Nordeste,Piauí,Sudoeste Piauiense,Floriano,Floriano,1,Federal,True,...,NaN,NaN,False,False,False,2203909,0,0,False,22

---

# ADEQUAÇÃO PROFESSOR

In [85]:
def readexcel(filename, dictFeatures) :
    
    df = pd.read_excel(filename, sheet_name=0, skiprows=[1], header=0, index_col=None)
        
    for feature in df.columns :
        if dictFeatures[feature] == int :
            df[feature] = df[feature].astype(int)
        if dictFeatures[feature] == float :
            df[feature] = df[feature].astype(float)
        if dictFeatures[feature] == bool :
            df[feature] = df[feature].astype(bool)
        if dictFeatures[feature] == "category" :
            df[feature] = df[feature].astype("category")
            
    return df

In [86]:
dtypeAdeqProf = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "EFT1" : float,
    "EFT2" : float,
    "EFT3" : float,
    "EFT4" : float,
    "EFT5" : float,
    "EFAI1" : float,
    "EFAI2" : float,
    "EFAI3" : float,
    "EFAI4" : float,
    "EFAI5" : float,
    "EFAF1" : float,
    "EFAF2" : float,
    "EFAF3" : float,
    "EFAF4" : float,
    "EFAF5" : float
}

In [87]:
adeq_prof2017 = readexcel('dados_extra/Adequacao_FormacaoProf_2017.xlsx', dtypeAdeqProf)

In [88]:
adeq_prof2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,EFT1,...,EFAI1,EFAI2,EFAI3,EFAI4,EFAI5,EFAF1,EFAF2,EFAF3,EFAF4,EFAF5
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,100.0
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024275,CEEJA LUIZ VAZ DE CAMOES,Urbana,Estadual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,100.0,0.0,0.0
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,48.5,...,87.5,0.0,12.5,0.0,0.0,27.3,0.0,72.7,0.0,0.0
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,71.4,...,83.3,0.0,0.0,0.0,16.7,55.6,0.0,33.3,11.1,0.0

---

# COMPLEXIDADE GESTÃO

In [89]:
dtypeComplexGestao = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "Nível de complexidade de gestão da escola" : "category"
}

In [90]:
complex_gestao2017 = readexcel('dados_extra/Complexidade_Gestao_2017.xlsx', dtypeComplexGestao)

In [91]:
complex_gestao2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,Nível de complexidade de gestão da escola
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,Nível 1
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024275,CEEJA LUIZ VAZ DE CAMOES,Urbana,Estadual,Nível 4
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,Nível 1
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,Nível 3
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,Nível 3

---

# ESFORÇO DOCENTE

In [92]:
dtypeEsfDoc = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "EFT1" : float,
    "EFT2" : float,
    "EFT3" : float,
    "EFT4" : float,
    "EFT5" : float,
    "EFT6" : float,
    "EFAI1" : float,
    "EFAI2" : float,
    "EFAI3" : float,
    "EFAI4" : float,
    "EFAI5" : float,
    "EFAI6" : float,
    "EFAF1" : float,
    "EFAF2" : float,
    "EFAF3" : float,
    "EFAF4" : float,
    "EFAF5" : float,
    "EFAF6" : float
}

In [93]:
esf_docente2017 = readexcel('dados_extra/Esforço_Docente_2017.xlsx', dtypeEsfDoc)

In [94]:
esf_docente2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,EFT1,...,EFAI3,EFAI4,EFAI5,EFAI6,EFAF1,EFAF2,EFAF3,EFAF4,EFAF5,EFAF6
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,100.0,...,NaN,NaN,NaN,NaN,100.0,0.0,0.0,0.0,0.0,0.0
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,100.0,...,NaN,NaN,NaN,NaN,100.0,0.0,0.0,0.0,0.0,0.0
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,50.0,...,0.0,25.0,0.0,0.0,20.0,0.0,40.0,20.0,20.0,0.0
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,31.2,...,0.0,28.6,0.0,0.0,0.0,0.0,0.0,90.0,0.0,10.0
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024682,EEEF EURIDICE LOPES PEDROSO,Urbana,Estadual,11.2,...,0.0,5.9,5.9,0.0,8.3,0.0,41.7,25.0,25.0,0.0

---

# MÉDIA ALUNOS

In [95]:
dtypeMedAlunos = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "EFT" : float,
    "EFAI" : float,
    "EFAF" : float,
    "EF1" : float,
    "EF2" : float,
    "EF3" : float,
    "EF4" : float,
    "EF5" : float,
    "EF6" : float,
    "EF7" : float,
    "EF8" : float,
    "EF9" : float,
    "Turmas Multietapa, Multi ou Correcão de Fluxo " : float
}

In [96]:
media_alunos2017 = readexcel('dados_extra/Media_Alunos_2017.xlsx', dtypeMedAlunos)

In [97]:
media_alunos2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,EFT,...,EF1,EF2,EF3,EF4,EF5,EF6,EF7,EF8,EF9,"Turmas Multietapa, Multi ou Correcão de Fluxo"
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,19.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.5
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,13.3,...,15.0,14.0,NaN,17.0,NaN,14.0,15.0,11.0,10.0,10.0
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,20.9,...,23.0,18.0,17.0,17.5,24.0,25.0,22.0,27.0,18.0,NaN
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024682,EEEF EURIDICE LOPES PEDROSO,Urbana,Estadual,28.7,...,NaN,NaN,25.5,30.3,29.6,31.0,30.3,31.0,NaN,14.0

---

# MÉDIA HORAS AULA

In [104]:
dtypeMedHorasAlunos = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "EFT" : float,
    "EFAI" : float,
    "EFAF" : float,
    "EF1" : float,
    "EF2" : float,
    "EF3" : float,
    "EF4" : float,
    "EF5" : float,
    "EF6" : float,
    "EF7" : float,
    "EF8" : float,
    "EF9" : float
}

In [105]:
media_horas_alunos2017 = readexcel('dados_extra/Media_Horas_Aula_2017.xlsx', dtypeMedHorasAlunos)

In [106]:
media_horas_alunos2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,EFT,...,EFAF,EF1,EF2,EF3,EF4,EF5,EF6,EF7,EF8,EF9
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,4.1,...,4.1,4.0,4.0,NaN,4.0,NaN,4.0,4.0,4.5,4.0
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024682,EEEF EURIDICE LOPES PEDROSO,Urbana,Estadual,4.0,...,4.0,NaN,NaN,4.0,4.0,4.0,4.0,4.0,4.0,NaN
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024828,EMEIEF IZIDORO STEDILE,Urbana,Municipal,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024917,EMEIEF JOSE BASILIO DA GAMA,Rural,Municipal,4.0,...,4.0,NaN,NaN,NaN,4.0,NaN,4.0,4.0,4.0,4.0

---

# Percentual Curso Superior

In [111]:
dtypePercCursoSup = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "EFT" : float,
    "EFAI" : float,
    "EFAF" : float
}

In [112]:
perc_curso_sup2017 = readexcel('dados_extra/Percentual_CursoSuperior_2017.xlsx', dtypePercCursoSup)

In [113]:
perc_curso_sup2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,EFT,EFAI,EFAF
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,0.0,NaN,0.0
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024275,CEEJA LUIZ VAZ DE CAMOES,Urbana,Estadual,NaN,NaN,NaN
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,100.0,NaN,100.0
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,100.0,100.0,100.0
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,87.5,85.7,90.0

---

# REGULARIDADE CORPO DOCENTE

In [116]:
dtypeRegCorpoDoc = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "Média do Indicador de Regularidade do Docente (IRD)" : float
}

In [117]:
reg_corpo_doc2017 = readexcel('dados_extra/Regularidade_Corpo_Docente_2017.xlsx', dtypeRegCorpoDoc)

In [118]:
reg_corpo_doc2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,Média do Indicador de Regularidade do Docente (IRD)
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,5.000000
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024275,CEEJA LUIZ VAZ DE CAMOES,Urbana,Estadual,3.462561
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,3.735335
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,3.311801
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,2.295415

---

# TAXA DE DISTORÇÃO IDADE

In [122]:
dtypeTxDistIdade = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "EFT" : float,
    "EFAI" : float,
    "EFAF" : float,
    "EF1" : float,
    "EF2" : float,
    "EF3" : float,
    "EF4" : float,
    "EF5" : float,
    "EF6" : float,
    "EF7" : float,
    "EF8" : float,
    "EF9" : float
}

In [123]:
tax_dist_idade2017 = readexcel('dados_extra/Taxa_DistorcaoIdade_2017.xlsx', dtypeTxDistIdade)

In [124]:
tax_dist_idade2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,EFT,...,EFAF,EF1,EF2,EF3,EF4,EF5,EF6,EF7,EF8,EF9
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,25.0,...,NaN,0.0,0.0,0.0,0.0,60.0,NaN,NaN,NaN,NaN
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,10.3,...,NaN,0.0,0.0,0.0,30.0,25.0,NaN,NaN,NaN,NaN
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,24.5,...,44.0,0.0,0.0,0.0,17.6,20.0,42.9,40.0,36.4,60.0
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,19.1,...,35.9,4.3,0.0,5.9,2.9,16.7,28.0,18.2,48.1,50.0
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024682,EEEF EURIDICE LOPES PEDROSO,Urbana,Estadual,14.8,...,19.5,NaN,NaN,7.8,12.2,16.1,14.0,24.2,22.6,NaN

---

# Taxa Distorção Idade

In [125]:
dtypeTaxDistIdade = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "EFT" : float,
    "EFAI" : float,
    "EFAF" : float,
    "EF1" : float,
    "EF2" : float,
    "EF3" : float,
    "EF4" : float,
    "EF5" : float,
    "EF6" : float,
    "EF7" : float,
    "EF8" : float,
    "EF9" : float
}

In [126]:
tax_dist_idade2017 = readexcel('dados_extra/Taxa_DistorcaoIdade_2017.xlsx', dtypeTxDistIdade)

In [127]:
tax_dist_idade2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,EFT,...,EFAF,EF1,EF2,EF3,EF4,EF5,EF6,EF7,EF8,EF9
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,25.0,...,NaN,0.0,0.0,0.0,0.0,60.0,NaN,NaN,NaN,NaN
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,10.3,...,NaN,0.0,0.0,0.0,30.0,25.0,NaN,NaN,NaN,NaN
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,24.5,...,44.0,0.0,0.0,0.0,17.6,20.0,42.9,40.0,36.4,60.0
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,19.1,...,35.9,4.3,0.0,5.9,2.9,16.7,28.0,18.2,48.1,50.0
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024682,EEEF EURIDICE LOPES PEDROSO,Urbana,Estadual,14.8,...,19.5,NaN,NaN,7.8,12.2,16.1,14.0,24.2,22.6,NaN

---

# Taxa Não Resposta

In [134]:
dtypeNaoResposta = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "EFT" : float,
    "EFAI" : float,
    "EFAF" : float,
    "EF1" : float,
    "EF2" : float,
    "EF3" : float,
    "EF4" : float,
    "EF5" : float,
    "EF6" : float,
    "EF7" : float,
    "EF8" : float,
    "EF9" : float
}

In [130]:
tax_nao_resposta2017 = readexcel('dados_extra/Taxa_NaoResposta_2017.xlsx', dtypeNaoResposta)

In [131]:
tax_nao_resposta2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,EFT,...,EFAF,EF1,EF2,EF3,EF4,EF5,EF6,EF7,EF8,EF9
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,0.0,...,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,0.0,...,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,2.8,...,3.8,6.7,0.0,0.0,0.0,0.0,0.0,0.0,9.1,10.0
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,1.0,...,1.1,4.3,0.0,0.0,0.0,0.0,0.0,0.0,4.2,0.0
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024682,EEEF EURIDICE LOPES PEDROSO,Urbana,Estadual,0.8,...,1.0,NaN,NaN,0.0,0.5,1.3,0.0,2.4,0.0,NaN

---

# TAXA RENDIMENTO ESCOLAS

In [137]:
dtypeRendEscolas = {
    "Ano" : int,
    "Região" : "category",
    "UF" : "category",
    "Código do Município" : object,
    "Nome do Município" : object,
    "Código da Escola" : object,
    "Nome da Escola" : object,
    "Localizacão" : "category",
    "Dependência Administrativa" : "category",
    "EF_TXAPR_T" : float,
    "EF_TXAPR_AI" : float,
    "EF_TXAPR_AF" : float,
    "EF_TXAPR_1" : float,
    "EF_TXAPR_2" : float,
    "EF_TXAPR_3" : float,
    "EF_TXAPR_4" : float,
    "EF_TXAPR_5" : float,
    "EF_TXAPR_6" : float,
    "EF_TXAPR_7" : float,
    "EF_TXAPR_8" : float,
    "EF_TXAPR_9" : float,
    "EF_TXREPR_T" : float,
    "EF_TXREPR_AI" : float,
    "EF_TXREPR_AF" : float,
    "EF_TXREPR_1" : float,
    "EF_TXREPR_2" : float,
    "EF_TXREPR_3" : float,
    "EF_TXREPR_4" : float,
    "EF_TXREPR_5" : float,
    "EF_TXREPR_6" : float,
    "EF_TXREPR_7" : float,
    "EF_TXREPR_8" : float,
    "EF_TXREPR_9" : float,
    "EF_TXABANDONO_T" : float,
    "EF_TXABANDONO_AI" : float,
    "EF_TXABANDONO_AF" : float,
    "EF_TXABANDONO_1" : float,
    "EF_TXABANDONO_2" : float,
    "EF_TXABANDONO_3" : float,
    "EF_TXABANDONO_4" : float,
    "EF_TXABANDONO_5" : float,
    "EF_TXABANDONO_6" : float,
    "EF_TXABANDONO_7" : float,
    "EF_TXABANDONO_8" : float,
    "EF_TXABANDONO_9" : float
}

In [138]:
tax_rend_escolas2017 = readexcel('dados_extra/TX_REND_ESCOLAS_2017.xlsx', dtypeRendEscolas)

In [139]:
tax_rend_escolas2017.head()

,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localizacão,Dependência Administrativa,EF_TXAPR_T,...,EF_TXABANDONO_AF,EF_TXABANDONO_1,EF_TXABANDONO_2,EF_TXABANDONO_3,EF_TXABANDONO_4,EF_TXABANDONO_5,EF_TXABANDONO_6,EF_TXABANDONO_7,EF_TXABANDONO_8,EF_TXABANDONO_9
0,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,61.5,...,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024291,EMMEF 7 DE SETEMBRO,Rural,Municipal,97.4,...,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024372,EMEIEF ANA NERY,Urbana,Municipal,91.5,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,6.6,0.0,11.1
3,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024666,EMEIEF BOA ESPERANCA,Rural,Municipal,88.3,...,3.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.8
4,2017,Norte,RO,1100015,Alta Floresta D'Oeste,11024682,EEEF EURIDICE LOPES PEDROSO,Urbana,Estadual,94.1,...,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN

---

# CRUZAMENTO BASES